name: Sync and Commit S3 Data

on:
  schedule:
    - cron: '43 16 * * *' # 混雑を避けるために毎日25時43分に実行
  workflow_dispatch: # 手動トリガー

jobs:
  fetch_and_commit:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-1

    - name: Fetch data from S3
      run: aws s3 sync s3://obsidian-til-miroscular ./content --delete

    - name: check for changes
      run: |
        git add -A
        git diff --staged --quiet || echo "git_changed=true" >> $GITHUB_ENV

    - name: test
      run: echo $git_changed

    - name: Commit changes
      if: env.git_changed == "true"
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        git add -A
        git commit -m 'Sync data with S3'
        git push origin v4
